name: Build Z80 Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Z80 Assembler
        run: sudo apt-get install z80asm

      - name: Assemble Z80 Code
        run: z80asm -b test.asm -o test.gba

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.gba
